server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: nextjs-bff
          uri: http://localhost:3000
          predicates:
            - Path=/,/products/**,/cart/**,/mypage/**
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/**
management:
  endpoints:
    web:
      exposure:
        include: health,info
